JAMES-3197 Maiklet processing should handle NoClassDefFoundError
Due to JAMES-3176, we ended up having ExtractMDNOriginalJMAPMessageId throwing NoClassDefFoundError.

This error is not handled by the mailet processor, resulting in a mailqueue nack, and generated an infinite loop on top of RabbitMQ.

This error can happen too when a user specifies a custom mailet with unsatisfied dependencies.

Thus, when a mailet, or a matcher throws a `NoClassDefFoundError` we should execute mailet error handling normally, and prevent that infinite loop.